### ISSUE TITLE
Monkeytype API response fails JSON parsing

### ISSUE THREAD

**Issue by zachstence** [vnphanquang/monkeytype-readme#1]
Hi Quang,

I'm seeing this error when running the action:
```
Error: invalid json response body at https://api.monkeytype.com/users/personalBests?mode=words&mode2=50 reason: Unexpected token < in JSON at position 0
```

Here is the full output of the action
```
with:
    monkeytype_api_key: ***
    mode: words
    mode2: 50
    style: for-the-badge
    logoVariant: one
    label: monkeytype
    github_token: ***
Parsing action input...
Getting badge URL...
Error: invalid json response body at https://api.monkeytype.com/users/personalBests?mode=words&mode2=50 reason: Unexpected token < in JSON at position 0
```

I tried a couple different configurations for the parameters with no luck. I have also tested my Monkeytype API key in Postman and I'm able to get a good response. As I can't get in the code and take a look at the JSON response, I don't really have a great way to debug. Any thoughts?

**Comment by vnphanquang** [comment]
@zachstence hey pal thanks for letting me now. Let me run some test and see what's up

**Comment by vnphanquang** [comment]
Update: the response status from monkeytype server is 503. This ONLY happens in github pipelines, however.

- Unit tests are all okay when run locally,
- calling the same requests from browser is also fine,
- `node-fetch` is tested and not the problem,
- running same code on `runkit` (a node playground) results in same 503 code. 

This is not making sense to me. All of the above suggests some kind of blocker from monkeytype server. I'm in contact with monkeytype devs for further support.

**Comment by zachstence** [comment]
@vnphanquang Any update from the Monkeytype devs?

**Comment by vnphanquang** [comment]
@zachstence yup it's cloudfare DDoS indeed. Sorry I've been travelling. Will create an issue in monkeytype github page as soon as I get home.

**Comment by vnphanquang** [comment]
Seems to be working fine for a while now. I'll close this issue for now. Please feel free to reopen otherwise

**Comment by vnphanquang** [comment]
Still failing from time to time in workflow run. Seems to be hit-and-miss.

For others coming to this thread, if you've experienced consistent failures in github actions, fallback to [using a static badge](https://github.com/vnphanquang/monkeytype-readme#static-usage) instead. Apologies there's nothing else I can do since this is handled by monkeytype server.
