### ISSUE TITLE
Error while running Actions

### ISSUE THREAD

**Issue by dharsan19** [vnphanquang/monkeytype-readme#2]
Hi Quang,
      I'm getting these error while running Github action
<img width="1421" alt="image" src="https://user-images.githubusercontent.com/104762761/207556028-e0f31be0-d10e-41f7-86eb-46100a6a37a7.png">

**Comment by vnphanquang** [comment]
Hello @dharsan19. Thanks for reporting, I'll look into it

**Comment by vnphanquang** [comment]
@dharsan19 you've set up `MONKEYTYPE_API_KEY` as [instructed in README](https://github.com/vnphanquang/monkeytype-readme#2-monkeytype-api-key) I assume? The error looks like you've not?

**Comment by dharsan19** [comment]
@vnphanquang i have done it as mentioned in the readme. But i Forgot to active the key in Moneytype. 
But after Doing this, i am getting this error

Error: FetchError: invalid json response body at https://api.monkeytype.com/users/personalBests?mode=time&mode2=30 reason: Unexpected token < in JSON at position 0

**Comment by vnphanquang** [comment]
@dharsan19 looks like your action just ran successfully.

![20221214_171924](https://user-images.githubusercontent.com/25895844/207569252-f724913f-f7ea-4cda-b419-72ddf629c410.png)

**Comment by dharsan19** [comment]
@vnphanquang After rerunning the Workflow It got fixed. Thank You So much.

**Comment by vnphanquang** [comment]
No problem, thanks for reporting. I've added a reminder in README to activate, and a runtime error to check for missing key.

closing this for now
